### MAKEFILE GENERATED BY AKB"
# BEGIN MAKEFILE
prepare:
	@echo "Building <Prepare>"
	@akb_prepare
build:
	@echo "Building <Build>" 
	@akb_build
clean:
	@echo "Building <Clean>"
	@akb_clean
# END MAKEFILE
